import { MigrationInterface, QueryRunner } from "typeorm";

export class FixedInitialMigration1769338021517 implements MigrationInterface {
    name = 'FixedInitialMigration1769338021517'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('admin', 'student', 'teacher')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "fullName" character varying, "role" "public"."user_role_enum" NOT NULL DEFAULT 'student', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "dob" TIMESTAMP, "education" character varying, "category" character varying, "location" character varying, "defaultLanguage" character varying, "profilePicture" character varying, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6620cd026ee2b231beac7cfe57" ON "user" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_e11e649824a45d8ed01d597fd9" ON "user" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."exam_type_enum" AS ENUM('real_exam', 'question_bank', 'previous_year_paper', 'live_exam')`);
        await queryRunner.query(`CREATE TABLE "exam" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."exam_type_enum" NOT NULL DEFAULT 'real_exam', "title" character varying NOT NULL, "description" character varying, "category" character varying, "isActive" boolean NOT NULL DEFAULT true, "isPremium" boolean NOT NULL DEFAULT false, "isPublished" boolean NOT NULL DEFAULT false, "price" double precision NOT NULL DEFAULT '0', "defaultPositiveMarks" double precision NOT NULL DEFAULT '1', "defaultNegativeMarks" double precision NOT NULL DEFAULT '0.25', "duration" integer NOT NULL DEFAULT '60', "isLive" boolean NOT NULL DEFAULT false, "startTime" TIMESTAMP, "endTime" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56071ab3a94aeac01f1b5ab74aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subject" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "icon" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "examId" uuid, CONSTRAINT "PK_12eee115462e38d62e5455fc054" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chapter" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "subjectId" uuid, CONSTRAINT "PK_275bd1c62bed7dff839680614ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "model" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "totalQuestions" integer NOT NULL DEFAULT '0', "duration" integer NOT NULL DEFAULT '60', "scheduledAt" TIMESTAMP, "chapterId" uuid, CONSTRAINT "PK_d6df271bba301d5cc79462912a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "options" text, "correctOptionId" character varying NOT NULL, "explanation" text, "topic" character varying NOT NULL DEFAULT 'General', "chapterId" uuid, "examId" uuid, "difficultyWeight" double precision NOT NULL DEFAULT '0.5', "positiveMarks" double precision NOT NULL DEFAULT '1', "negativeMarks" double precision NOT NULL DEFAULT '0.25', "correctCount" integer NOT NULL DEFAULT '0', "totalAttempts" integer NOT NULL DEFAULT '0', "subjectId" uuid, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0865fc43f9c9e4a3c958a25570" ON "question" ("difficultyWeight") `);
        await queryRunner.query(`CREATE TYPE "public"."quality_flag_type_enum" AS ENUM('INCORRECT_ANSWER', 'TYPO', 'UNCLEAR_QUESTION', 'OFFENSIVE_CONTENT', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."quality_flag_status_enum" AS ENUM('PENDING', 'REVIEWED', 'RESOLVED', 'DISMISSED')`);
        await queryRunner.query(`CREATE TABLE "quality_flag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "questionId" uuid, "reporterId" uuid, "type" "public"."quality_flag_type_enum" NOT NULL DEFAULT 'OTHER', "description" text NOT NULL, "status" "public"."quality_flag_status_enum" NOT NULL DEFAULT 'PENDING', "adminNotes" text, "reviewedById" uuid, "reviewedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c2beda944bf286f487d94ced568" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pass_passtype_enum" AS ENUM('SUBSCRIPTION', 'ONE_TIME', 'LIFETIME')`);
        await queryRunner.query(`CREATE TABLE "pass" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "durationDays" integer NOT NULL, "features" jsonb NOT NULL DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "isPopular" boolean NOT NULL DEFAULT false, "passType" "public"."pass_passtype_enum" NOT NULL DEFAULT 'SUBSCRIPTION', "maxExams" integer NOT NULL DEFAULT '0', "includedExamTypes" jsonb NOT NULL DEFAULT '[]', "excludedExamIds" jsonb NOT NULL DEFAULT '[]', "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f177d7f9a16271fab41c51876e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5d832e41c29d69b059577bd76a" ON "pass" ("isActive") `);
        await queryRunner.query(`CREATE TABLE "user_pass" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "passId" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "razorpayOrderId" character varying, "razorpayPaymentId" character varying, "couponCode" character varying, "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "paymentStatus" character varying NOT NULL DEFAULT 'PENDING', "purchaseDate" TIMESTAMP NOT NULL, "expiryDate" TIMESTAMP NOT NULL, "status" character varying NOT NULL DEFAULT 'ACTIVE', "autoRenew" boolean NOT NULL DEFAULT false, "cancelledAt" TIMESTAMP, "cancellationReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_89fbf1eb98fc1d9d8e223822e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_363986c9c5e2ce0af3cc458ff2" ON "user_pass" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e29a0259802a92fcbc1aa08d9" ON "user_pass" ("expiryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_716cfa8cc54f69be0b82f9e8b7" ON "user_pass" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c64e70eb4882112f5860c28f44" ON "user_pass" ("userId", "status") `);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "type" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "type" character varying NOT NULL DEFAULT 'general', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2a6ef77141a01b8ac31f514cfc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_campaign" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "subject" character varying NOT NULL, "body" text NOT NULL, "recipientType" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'DRAFT', "sentAt" TIMESTAMP, "sentCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_140462ad4b82245fec89e5a3976" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupon" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "discountType" character varying NOT NULL, "discountValue" double precision NOT NULL, "maxUses" integer, "usedCount" integer NOT NULL DEFAULT '0', "expiresAt" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_62d3c5b0ce63a82c48e86d904bc" UNIQUE ("code"), CONSTRAINT "PK_fcbe9d72b60eed35f46dc35a682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_gamification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "totalXp" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "currentStreak" integer NOT NULL DEFAULT '0', "longestStreak" integer NOT NULL DEFAULT '0', "lastActivityDate" date, "badges" jsonb NOT NULL DEFAULT '[]', "testsCompleted" integer NOT NULL DEFAULT '0', "correctAnswers" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4f2db3f62e0aaa6a40540e7c27e" UNIQUE ("userId"), CONSTRAINT "PK_db92d24015cda11113d1a3cad80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "daily_challenge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "challengeType" character varying(50) NOT NULL, "targetValue" integer NOT NULL, "rewardXp" integer NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4120f12b9bdf6c11b5d5f30036c" UNIQUE ("date"), CONSTRAINT "PK_3c8785526c5d3e52a62b0b1fc62" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_challenge_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "challengeId" uuid NOT NULL, "currentValue" integer NOT NULL DEFAULT '0', "completed" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP, CONSTRAINT "PK_1e0e12fc9b849b6a125348acd70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attempt" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "examId" uuid, "score" double precision NOT NULL, "totalQuestions" integer NOT NULL, "correctAnswers" integer NOT NULL, "timeTaken" integer NOT NULL, "accuracy" double precision NOT NULL DEFAULT '0', "userAnswers" text, "insights" text, "questionTimings" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "modelId" uuid, CONSTRAINT "PK_5f822b29b3128d1c65d3d6c193d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_65b233eb9155519df0f7255d20" ON "attempt" ("examId") `);
        await queryRunner.query(`CREATE INDEX "IDX_28e7109ffc24275d78740c83f3" ON "attempt" ("score") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bf79fee22dbe22c6cab799d7b" ON "attempt" ("timeTaken") `);
        await queryRunner.query(`CREATE INDEX "IDX_834158f1d3f3c3a8299f56b9bc" ON "attempt" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d408436aeaa404b2fdd030b55" ON "attempt" ("score", "timeTaken") `);
        await queryRunner.query(`CREATE TABLE "response" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "selectedOptionId" character varying NOT NULL, "isCorrect" boolean NOT NULL, "timeSpent" integer, "confidence" double precision, "wasSkipped" boolean NOT NULL DEFAULT false, "wasReviewed" boolean NOT NULL DEFAULT false, "answeredAt" TIMESTAMP NOT NULL DEFAULT now(), "attemptId" uuid, "questionId" uuid, CONSTRAINT "PK_f64544baf2b4dc48ba623ce768f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_972fd71a09bab57f062fdcfdfe" ON "response" ("attemptId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dfd952a4d26cf661248efec5f3" ON "response" ("questionId") `);
        await queryRunner.query(`CREATE TABLE "purchase" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stripeSessionId" character varying, "razorpayOrderId" character varying, "razorpayPaymentId" character varying, "amount" double precision NOT NULL, "couponCode" character varying, "discountAmount" double precision NOT NULL DEFAULT '0', "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "examId" uuid, CONSTRAINT "PK_86cc2ebeb9e17fc9c0774b05f69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question_flag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reason" character varying NOT NULL, "description" text NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "adminNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "questionId" uuid, "reportedById" uuid, CONSTRAINT "PK_dd883c69ded6b6c05a901e41ec7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "filename" character varying NOT NULL, "url" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "senderId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3cc0d85193aade457d3077dd06b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_chat_conversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bd32361512fc47c6e1b86691f28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_chat_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversationId" uuid NOT NULL, "role" character varying(20) NOT NULL, "content" text NOT NULL, "context" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_55019f66ea41b836f50c5aaf2b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_usage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "date" date NOT NULL, "requestCount" integer NOT NULL DEFAULT '0', "totalTokens" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3dddab3a15520a9c3eba859195d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8e36c687d8b8859c62a6f9cb13" ON "ai_usage" ("userId", "date") `);
        await queryRunner.query(`CREATE TABLE "question_explanation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "questionId" uuid NOT NULL, "contextExamId" uuid, "aiExplanation" text NOT NULL, "adminApprovedExplanation" text, "isVerified" boolean NOT NULL DEFAULT false, "helpfulCount" integer NOT NULL DEFAULT '0', "notHelpfulCount" integer NOT NULL DEFAULT '0', "averageRating" double precision NOT NULL DEFAULT '0', "viewCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_81eebb6fab0e455caffedd0b2ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_QE_QUESTION" ON "question_explanation" ("questionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_QE_QUESTION_ID" ON "question_explanation" ("questionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_QE_CONTEXT_EXAM_ID" ON "question_explanation" ("contextExamId") `);
        await queryRunner.query(`CREATE TABLE "user_topic_mastery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "topic" character varying(255) NOT NULL, "subjectId" uuid, "masteryScore" double precision NOT NULL DEFAULT '0', "totalAttempts" integer NOT NULL DEFAULT '0', "correctAttempts" integer NOT NULL DEFAULT '0', "lastPracticedAt" TIMESTAMP, "lastErrorPattern" character varying(255), "cognitiveAdvice" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_819544a05c06dcfbeef5696a8bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "learning_path" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "recommendedTopics" jsonb NOT NULL DEFAULT '[]', "weakAreas" jsonb NOT NULL DEFAULT '[]', "strongAreas" jsonb NOT NULL DEFAULT '[]', "generatedAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_54e28a4357911185890600bfaf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exam_questions_question" ("examId" uuid NOT NULL, "questionId" uuid NOT NULL, CONSTRAINT "PK_819e09c139d395314f8ca9c0e50" PRIMARY KEY ("examId", "questionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11295ef1e6332790d25510c17b" ON "exam_questions_question" ("examId") `);
        await queryRunner.query(`CREATE INDEX "IDX_28266c51d2322010c18960f486" ON "exam_questions_question" ("questionId") `);
        await queryRunner.query(`CREATE TABLE "exam_models" ("examId" uuid NOT NULL, "modelId" uuid NOT NULL, CONSTRAINT "PK_12d65b6c4f94f25b39c40ffd9dd" PRIMARY KEY ("examId", "modelId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9405487e218a9693ac97243344" ON "exam_models" ("examId") `);
        await queryRunner.query(`CREATE INDEX "IDX_83d03c5fa4be4d97fbbd97aaf5" ON "exam_models" ("modelId") `);
        await queryRunner.query(`CREATE TABLE "model_questions" ("modelId" uuid NOT NULL, "questionId" uuid NOT NULL, CONSTRAINT "PK_4a1532ab7d48f377de3bea67ac1" PRIMARY KEY ("modelId", "questionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f00ac6ef163977e92953951ff" ON "model_questions" ("modelId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5daf34ec763842f9905962130a" ON "model_questions" ("questionId") `);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "recipientType"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "sentCount"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "recipientType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "sentCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "scheduledAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "recipientCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "successCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "failureCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "targetAudience" text`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."email_campaign_status_enum" AS ENUM('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'FAILED')`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "status" "public"."email_campaign_status_enum" NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "subject" ADD CONSTRAINT "FK_6da3060e3028c4226ade815a727" FOREIGN KEY ("examId") REFERENCES "exam"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chapter" ADD CONSTRAINT "FK_0f71d20601ab4944679f398990d" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model" ADD CONSTRAINT "FK_c56e28883d01c4f74f8af862269" FOREIGN KEY ("chapterId") REFERENCES "chapter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_e924e3b8137111256e04c8f7500" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_5c2654a2f9b6631a764a6ce2a0c" FOREIGN KEY ("chapterId") REFERENCES "chapter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_286bbf761d3af4e2fcac4a634d5" FOREIGN KEY ("examId") REFERENCES "exam"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_flag" ADD CONSTRAINT "FK_fe21c4fb1f56b41ac89eaf2d896" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_flag" ADD CONSTRAINT "FK_a20489482197fad33a7292bfcce" FOREIGN KEY ("reporterId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quality_flag" ADD CONSTRAINT "FK_272f69a90c3f4d22eda83ea2a73" FOREIGN KEY ("reviewedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_pass" ADD CONSTRAINT "FK_363986c9c5e2ce0af3cc458ff2d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_pass" ADD CONSTRAINT "FK_9bbc6500a535f49c757d1aae93c" FOREIGN KEY ("passId") REFERENCES "pass"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_1ced25315eb974b73391fb1c81b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_gamification" ADD CONSTRAINT "FK_4f2db3f62e0aaa6a40540e7c27e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_challenge_progress" ADD CONSTRAINT "FK_20f4631621fd4bf1bd20e81317d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_challenge_progress" ADD CONSTRAINT "FK_e3dd366a79db0493839dfd8eae3" FOREIGN KEY ("challengeId") REFERENCES "daily_challenge"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attempt" ADD CONSTRAINT "FK_dd8844876037b478f5bb859512e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attempt" ADD CONSTRAINT "FK_c99a73cb570a472226c0bd17e25" FOREIGN KEY ("modelId") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attempt" ADD CONSTRAINT "FK_65b233eb9155519df0f7255d20e" FOREIGN KEY ("examId") REFERENCES "exam"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "response" ADD CONSTRAINT "FK_972fd71a09bab57f062fdcfdfec" FOREIGN KEY ("attemptId") REFERENCES "attempt"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "response" ADD CONSTRAINT "FK_dfd952a4d26cf661248efec5f37" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase" ADD CONSTRAINT "FK_33520b6c46e1b3971c0a649d38b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase" ADD CONSTRAINT "FK_a64bc6c94996f6705b3a84f47ad" FOREIGN KEY ("examId") REFERENCES "exam"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_flag" ADD CONSTRAINT "FK_681f19a416574b0661ed6e3e730" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_flag" ADD CONSTRAINT "FK_de197411c841c82d4e8d8f9408d" FOREIGN KEY ("reportedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message" ADD CONSTRAINT "FK_a2be22c99b34156574f4e02d0a0" FOREIGN KEY ("senderId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_chat_conversation" ADD CONSTRAINT "FK_8650c1afcc4138a6f553f1e4030" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_chat_message" ADD CONSTRAINT "FK_977abe045d7c5a0d3db31a6f958" FOREIGN KEY ("conversationId") REFERENCES "ai_chat_conversation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_explanation" ADD CONSTRAINT "FK_e6ac7606742bafbfe4509157a35" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_explanation" ADD CONSTRAINT "FK_b973fe5fd1d313da4dcdcf28422" FOREIGN KEY ("contextExamId") REFERENCES "exam"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_topic_mastery" ADD CONSTRAINT "FK_c0ea56cb6641133bef1d8f351f8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_topic_mastery" ADD CONSTRAINT "FK_0dacee67d1bdc6adf5c9864221d" FOREIGN KEY ("subjectId") REFERENCES "subject"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "learning_path" ADD CONSTRAINT "FK_2f4a3dc23aa7e56fabc7604a95b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam_questions_question" ADD CONSTRAINT "FK_11295ef1e6332790d25510c17b4" FOREIGN KEY ("examId") REFERENCES "exam"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_questions_question" ADD CONSTRAINT "FK_28266c51d2322010c18960f4862" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exam_models" ADD CONSTRAINT "FK_9405487e218a9693ac972433440" FOREIGN KEY ("examId") REFERENCES "exam"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "exam_models" ADD CONSTRAINT "FK_83d03c5fa4be4d97fbbd97aaf54" FOREIGN KEY ("modelId") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model_questions" ADD CONSTRAINT "FK_6f00ac6ef163977e92953951ff7" FOREIGN KEY ("modelId") REFERENCES "model"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "model_questions" ADD CONSTRAINT "FK_5daf34ec763842f9905962130a1" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "model_questions" DROP CONSTRAINT "FK_5daf34ec763842f9905962130a1"`);
        await queryRunner.query(`ALTER TABLE "model_questions" DROP CONSTRAINT "FK_6f00ac6ef163977e92953951ff7"`);
        await queryRunner.query(`ALTER TABLE "exam_models" DROP CONSTRAINT "FK_83d03c5fa4be4d97fbbd97aaf54"`);
        await queryRunner.query(`ALTER TABLE "exam_models" DROP CONSTRAINT "FK_9405487e218a9693ac972433440"`);
        await queryRunner.query(`ALTER TABLE "exam_questions_question" DROP CONSTRAINT "FK_28266c51d2322010c18960f4862"`);
        await queryRunner.query(`ALTER TABLE "exam_questions_question" DROP CONSTRAINT "FK_11295ef1e6332790d25510c17b4"`);
        await queryRunner.query(`ALTER TABLE "learning_path" DROP CONSTRAINT "FK_2f4a3dc23aa7e56fabc7604a95b"`);
        await queryRunner.query(`ALTER TABLE "user_topic_mastery" DROP CONSTRAINT "FK_0dacee67d1bdc6adf5c9864221d"`);
        await queryRunner.query(`ALTER TABLE "user_topic_mastery" DROP CONSTRAINT "FK_c0ea56cb6641133bef1d8f351f8"`);
        await queryRunner.query(`ALTER TABLE "question_explanation" DROP CONSTRAINT "FK_b973fe5fd1d313da4dcdcf28422"`);
        await queryRunner.query(`ALTER TABLE "question_explanation" DROP CONSTRAINT "FK_e6ac7606742bafbfe4509157a35"`);
        await queryRunner.query(`ALTER TABLE "ai_chat_message" DROP CONSTRAINT "FK_977abe045d7c5a0d3db31a6f958"`);
        await queryRunner.query(`ALTER TABLE "ai_chat_conversation" DROP CONSTRAINT "FK_8650c1afcc4138a6f553f1e4030"`);
        await queryRunner.query(`ALTER TABLE "chat_message" DROP CONSTRAINT "FK_a2be22c99b34156574f4e02d0a0"`);
        await queryRunner.query(`ALTER TABLE "question_flag" DROP CONSTRAINT "FK_de197411c841c82d4e8d8f9408d"`);
        await queryRunner.query(`ALTER TABLE "question_flag" DROP CONSTRAINT "FK_681f19a416574b0661ed6e3e730"`);
        await queryRunner.query(`ALTER TABLE "purchase" DROP CONSTRAINT "FK_a64bc6c94996f6705b3a84f47ad"`);
        await queryRunner.query(`ALTER TABLE "purchase" DROP CONSTRAINT "FK_33520b6c46e1b3971c0a649d38b"`);
        await queryRunner.query(`ALTER TABLE "response" DROP CONSTRAINT "FK_dfd952a4d26cf661248efec5f37"`);
        await queryRunner.query(`ALTER TABLE "response" DROP CONSTRAINT "FK_972fd71a09bab57f062fdcfdfec"`);
        await queryRunner.query(`ALTER TABLE "attempt" DROP CONSTRAINT "FK_65b233eb9155519df0f7255d20e"`);
        await queryRunner.query(`ALTER TABLE "attempt" DROP CONSTRAINT "FK_c99a73cb570a472226c0bd17e25"`);
        await queryRunner.query(`ALTER TABLE "attempt" DROP CONSTRAINT "FK_dd8844876037b478f5bb859512e"`);
        await queryRunner.query(`ALTER TABLE "user_challenge_progress" DROP CONSTRAINT "FK_e3dd366a79db0493839dfd8eae3"`);
        await queryRunner.query(`ALTER TABLE "user_challenge_progress" DROP CONSTRAINT "FK_20f4631621fd4bf1bd20e81317d"`);
        await queryRunner.query(`ALTER TABLE "user_gamification" DROP CONSTRAINT "FK_4f2db3f62e0aaa6a40540e7c27e"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_1ced25315eb974b73391fb1c81b"`);
        await queryRunner.query(`ALTER TABLE "user_pass" DROP CONSTRAINT "FK_9bbc6500a535f49c757d1aae93c"`);
        await queryRunner.query(`ALTER TABLE "user_pass" DROP CONSTRAINT "FK_363986c9c5e2ce0af3cc458ff2d"`);
        await queryRunner.query(`ALTER TABLE "quality_flag" DROP CONSTRAINT "FK_272f69a90c3f4d22eda83ea2a73"`);
        await queryRunner.query(`ALTER TABLE "quality_flag" DROP CONSTRAINT "FK_a20489482197fad33a7292bfcce"`);
        await queryRunner.query(`ALTER TABLE "quality_flag" DROP CONSTRAINT "FK_fe21c4fb1f56b41ac89eaf2d896"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_286bbf761d3af4e2fcac4a634d5"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_5c2654a2f9b6631a764a6ce2a0c"`);
        await queryRunner.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_e924e3b8137111256e04c8f7500"`);
        await queryRunner.query(`ALTER TABLE "model" DROP CONSTRAINT "FK_c56e28883d01c4f74f8af862269"`);
        await queryRunner.query(`ALTER TABLE "chapter" DROP CONSTRAINT "FK_0f71d20601ab4944679f398990d"`);
        await queryRunner.query(`ALTER TABLE "subject" DROP CONSTRAINT "FK_6da3060e3028c4226ade815a727"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."email_campaign_status_enum"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "status" character varying NOT NULL DEFAULT 'DRAFT'`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "targetAudience"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "failureCount"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "successCount"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "recipientCount"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "scheduledAt"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "sentCount"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "recipientType"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "body"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "sentCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "recipientType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "body" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "email_campaign" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5daf34ec763842f9905962130a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f00ac6ef163977e92953951ff"`);
        await queryRunner.query(`DROP TABLE "model_questions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83d03c5fa4be4d97fbbd97aaf5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9405487e218a9693ac97243344"`);
        await queryRunner.query(`DROP TABLE "exam_models"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28266c51d2322010c18960f486"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11295ef1e6332790d25510c17b"`);
        await queryRunner.query(`DROP TABLE "exam_questions_question"`);
        await queryRunner.query(`DROP TABLE "learning_path"`);
        await queryRunner.query(`DROP TABLE "user_topic_mastery"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_QE_CONTEXT_EXAM_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_QE_QUESTION_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_QE_QUESTION"`);
        await queryRunner.query(`DROP TABLE "question_explanation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e36c687d8b8859c62a6f9cb13"`);
        await queryRunner.query(`DROP TABLE "ai_usage"`);
        await queryRunner.query(`DROP TABLE "ai_chat_message"`);
        await queryRunner.query(`DROP TABLE "ai_chat_conversation"`);
        await queryRunner.query(`DROP TABLE "chat_message"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TABLE "question_flag"`);
        await queryRunner.query(`DROP TABLE "purchase"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfd952a4d26cf661248efec5f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_972fd71a09bab57f062fdcfdfe"`);
        await queryRunner.query(`DROP TABLE "response"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d408436aeaa404b2fdd030b55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_834158f1d3f3c3a8299f56b9bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bf79fee22dbe22c6cab799d7b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28e7109ffc24275d78740c83f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_65b233eb9155519df0f7255d20"`);
        await queryRunner.query(`DROP TABLE "attempt"`);
        await queryRunner.query(`DROP TABLE "user_challenge_progress"`);
        await queryRunner.query(`DROP TABLE "daily_challenge"`);
        await queryRunner.query(`DROP TABLE "user_gamification"`);
        await queryRunner.query(`DROP TABLE "coupon"`);
        await queryRunner.query(`DROP TABLE "email_campaign"`);
        await queryRunner.query(`DROP TABLE "notification_template"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c64e70eb4882112f5860c28f44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_716cfa8cc54f69be0b82f9e8b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e29a0259802a92fcbc1aa08d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_363986c9c5e2ce0af3cc458ff2"`);
        await queryRunner.query(`DROP TABLE "user_pass"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d832e41c29d69b059577bd76a"`);
        await queryRunner.query(`DROP TABLE "pass"`);
        await queryRunner.query(`DROP TYPE "public"."pass_passtype_enum"`);
        await queryRunner.query(`DROP TABLE "quality_flag"`);
        await queryRunner.query(`DROP TYPE "public"."quality_flag_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quality_flag_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0865fc43f9c9e4a3c958a25570"`);
        await queryRunner.query(`DROP TABLE "question"`);
        await queryRunner.query(`DROP TABLE "model"`);
        await queryRunner.query(`DROP TABLE "chapter"`);
        await queryRunner.query(`DROP TABLE "subject"`);
        await queryRunner.query(`DROP TABLE "exam"`);
        await queryRunner.query(`DROP TYPE "public"."exam_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e11e649824a45d8ed01d597fd9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6620cd026ee2b231beac7cfe57"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
    }

}
