import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateExamPDF = (exam: any, questions: any[]) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(41, 128, 185); // Blue color
    doc.text(exam.title || 'Exam Paper', pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Duration: ${exam.duration || 60} mins | Total Questions: ${questions.length}`, pageWidth / 2, 28, { align: 'center' });
    doc.line(20, 32, pageWidth - 20, 32);

    let yPos = 40;

    questions.forEach((q, index) => {
        // Page break check
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }

        // Question Text
        doc.setFontSize(12);
        doc.setTextColor(0);
        doc.setFont('helvetica', 'bold');

        const questionText = `Q${index + 1}. ${q.content}`;
        const splitText = doc.splitTextToSize(questionText, pageWidth - 40);
        doc.text(splitText, 20, yPos);
        yPos += splitText.length * 7;

        // Options
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);

        q.options.forEach((opt: any, i: number) => {
            if (yPos > 270) {
                doc.addPage();
                yPos = 20;
            }

            const isCorrect = q.correctOptionId === opt.id;
            const prefix = String.fromCharCode(97 + i); // a, b, c, d

            if (isCorrect) {
                doc.setTextColor(39, 174, 96); // Green for correct answer in key (optional)
                doc.setFont('helvetica', 'bold');
            } else {
                doc.setTextColor(80);
                doc.setFont('helvetica', 'normal');
            }

            doc.text(`(${prefix}) ${opt.text}`, 25, yPos);
            yPos += 7;
        });

        // Solution / Explanation
        if (q.explanation) {
            if (yPos > 260) {
                doc.addPage();
                yPos = 20;
            }
            yPos += 2;
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.setFont('helvetica', 'italic');
            const explanationText = `Explanation: ${q.explanation}`;
            const splitExpl = doc.splitTextToSize(explanationText, pageWidth - 40);
            doc.text(splitExpl, 20, yPos);
            yPos += splitExpl.length * 5;
        }

        yPos += 10; // Spacing between questions
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${pageCount} | Generated by eRankUp`, pageWidth / 2, 290, { align: 'center' });
    }

    doc.save(`${exam.title?.replace(/\s+/g, '_')}_Paper.pdf`);
};
